resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/DigitalInnovation/touchlabs-webpack.git
      branch: concourse

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
  - task: install
    config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
          privileged: true
        inputs:
          - name: sources
            path: repo
        run:
          path: ../repo/concourse/installAndTest.sh
          dir: repo



