resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/DigitalInnovation/touchlabs-webpack.git
      branch: concourse

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
