resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/DigitalInnovation/touchlabs-webpack.git
      branch: ci

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
  - task: install
    config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: node, tag: "5.12" }
        inputs:
          - name: sources
            path: repo
        run:
          path: ../repo/ci/build.sh
          dir: repo
